pipeline {
    agent{
        docker { image 'node:7-alpine' }
    }

    stages{
        stage ('Compile Stage'){
            steps {
                sh 'node --version'
            }
        }

        stage('Testing Stage'){
            steps{
                withMaven(maven : 'maven_3_6_0'){
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Deployment Stage'){
            steps{
                withMaven(maven : 'maven_3_6_0'){
                    sh 'mvn clean compile'
                }
            }
        }
    }
}
