pipeline {
    agent any 
    stages{
        stage ('Compile Stage'){
            steps {
                sh 'javac C:/Program Files (x86)/Jenkins/workspace/p1/src/main/java/laboratorio/Controller.java| java Controller'
            }
        }

        stage('Testing Stage'){
            steps{
                withMaven(maven : 'maven_3_6_0'){
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Deployment Stage'){
            steps{
                withMaven(maven : 'maven_3_6_0'){
                    sh 'mvn clean compile'
                }
            }
        }
    }
}
