pipeline {
    agent any

    stages{
        stage ('Compile Stage'){
            steps{
                steps {
                    sh 'echo "Hello World"'
                    sh '''
                        echo "Multiline shell steps works too"
                        ls -lah
                    '''
                }
            }
        }

        stage('Testing Stage'){
            steps{
                withMaven(maven : 'maven_3_6_0'){
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Deployment Stage'){
            steps{
                withMaven(maven : 'maven_3_6_0'){
                    sh 'mvn clean compile'
                }
            }
        }
    }
}
